[package]
name = "zipcrawl"
version = "2.2.0"
edition = "2024"
authors = ["SirCesarium"]
description = "Explore and stream ZIP archives without even extracting them."
license = "MIT"
repository = "https://github.com/SirCesarium/zipcrawl"
readme = "README.md"
keywords = ["zip", "cli", "explorer", "grep", "tree"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
colored = "3.1.1"
miette = { version = "7.6.0", features = ["fancy"] }
regex = "1.12.3"
thiserror = "2.0.18"
zip = "8.6.0"
clap = { version = "4.6.1", features = ["derive"], optional = true }
glob = "0.3.3"
similar = "3.1.1"
minus = { version = "5.7.1", features = ["static_output"] }
syntect = { version = "5.3.0", features = ["default-fancy"], default-features = false }
clap_complete = { version = "4.6.5", features = ["unstable-dynamic"], optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
toml = { version = "0.8", optional = true }
tempfile = "3.27.0"

[features]
default = ["nerdfonts", "cli"]
nerdfonts = []
cli = ["dep:clap", "dep:clap_complete"]
compress = []
serde = ["dep:serde", "dep:serde_json", "dep:toml"]

[dev-dependencies]
